#!/bin/bash
source /boot/config/plugins/openvpnclient/openvpnclient.cfg
if [[ "$START_ON_MOUNT" = "yes" ]]; then
        logger "Starting OpenVPN Client"
        /etc/rc.d/rc.openvpnclient start | logger
fi
